spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lvidatabase
    driver-class-name: org.postgresql.Driver
    username: lvidb
    password: 12345
  jpa:
    show-sql: true
    open-in-view: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  data:
    rest:
      base-path: /lvi
springdoc:
  api-docs:
    path: /lvi-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true